/**
 * Action Type
 */

'use strict';

import keyMirror from 'keyMirror';

export default keyMirror({

    // Route action types
    SET_CURRENT_ROUTE: 'SET_CURRENT_ROUTE',

    // All Suite Actions
    SESSION_RECEIVE_DATA: 'SESSION_RECEIVE_DATA',
    SESSION_REQUEST_DATA: 'SESSION_REQUEST_DATA',

    // All Suite Actions
    SUITES_RECEIVE_DATA: 'SUITES_RECEIVE_DATA',
    SUITES_REQUEST_DATA: 'SUITES_REQUEST_DATA',
    SUITE_RECEIVE_DATA: 'SUITE_RECEIVE_DATA',
    SUITE_REQUEST_DATA: 'SUITE_REQUEST_DATA',
    SUITES_RESET_DATA: 'SUITES_RESET_DATA',

    // All Place Actions
    PLACE_RECEIVE_DATA: 'PLACE_RECEIVE_DATA',
    PLACE_REQUEST_DATA: 'PLACE_REQUEST_DATA',

    // All Menu Actions
    MENU_RECEIVE_DATA: 'MENU_RECEIVE_DATA',
    MENU_REQUEST_DATA: 'MENU_REQUEST_DATA',

    // All Cart Actions
    CART_RECEIVE_DATA: 'CART_RECEIVE_DATA',
    CART_REQUEST_DATA: 'CART_REQUEST_DATA',

    // All Order Actions
    ORDER_RECEIVE_DATA: 'ORDER_RECEIVE_DATA',
    ORDER_REQUEST_DATA: 'ORDER_REQUEST_DATA'
});
